import Foundation
import SourceKittenFramework

// Usage: GeneratePreviewMapperTool [swift-file...] --output <output-path>
var inputFiles: [String] = []
var outputPath: String?

var argIterator = CommandLine.arguments.dropFirst().makeIterator()
while let arg = argIterator.next() {
    if arg == "--output" {
        outputPath = argIterator.next()
    } else {
        inputFiles.append(arg)
    }
}

guard let outputPath else {
    fputs("error: --output argument is required\n", stderr)
    exit(1)
}

// Recursively walk a SourceKit structure dictionary and collect names of types/extensions
// that list AutoPreviewable in their inherited types.
func findConformances(in dict: [String: SourceKitRepresentable]) -> [String] {
    var results: [String] = []

    let kind = dict[SwiftDocKey.kind.rawValue] as? String
    let name = dict[SwiftDocKey.name.rawValue] as? String

    let declarationKinds: Set<String> = [
        SwiftDeclarationKind.struct.rawValue,
        SwiftDeclarationKind.class.rawValue,
        SwiftDeclarationKind.extension.rawValue,
        SwiftDeclarationKind.actor.rawValue,
    ]

    if let kind, declarationKinds.contains(kind),
       let name,
       let inheritedValue = dict[SwiftDocKey.inheritedtypes.rawValue],
       let inheritedTypes = inheritedValue as? [SourceKitRepresentable] {
        let conformsToPreviewTestableView = inheritedTypes.contains { entry in
            guard let entryDict = entry as? [String: SourceKitRepresentable] else { return false }
            return (entryDict[SwiftDocKey.name.rawValue] as? String) == "AutoPreviewable"
        }
        if conformsToPreviewTestableView {
            results.append(name)
        }
    }

    // Recurse into nested declarations
    if let subValue = dict[SwiftDocKey.substructure.rawValue],
       let substructure = subValue as? [SourceKitRepresentable] {
        for item in substructure {
            if let itemDict = item as? [String: SourceKitRepresentable] {
                results.append(contentsOf: findConformances(in: itemDict))
            }
        }
    }

    return results
}

var conformingTypes: [String] = []

for filePath in inputFiles {
    guard let file = File(path: filePath) else {
        fputs("warning: could not read \(filePath)\n", stderr)
        continue
    }
    do {
        let structure = try Structure(file: file)
        for typeName in findConformances(in: structure.dictionary) where !conformingTypes.contains(typeName) {
            conformingTypes.append(typeName)
        }
    } catch {
        fputs("warning: could not parse \(filePath): \(error)\n", stderr)
    }
}

conformingTypes.sort()

// Emit PreviewTestableMapper.swift
var lines = [
    "// Generated by GeneratePreviewMapper — do not edit.",
    "// This file is auto-generated at build time and is not tracked in the project tree.",
    "",
    "struct PreviewTestableMapper {",
    "    static let previewTestableViews: [String] = [",
]
for typeName in conformingTypes {
    lines.append("        \"\(typeName)\",")
}
lines += ["    ]", "}"]

do {
    try (lines.joined(separator: "\n") + "\n").write(toFile: outputPath, atomically: true, encoding: .utf8)
} catch {
    fputs("error: could not write to \(outputPath): \(error.localizedDescription)\n", stderr)
    exit(1)
}
