/// Renders the source text for the generated `TestablePreviews` class from
/// whatever `AutoPreviewable`-conforming types were discovered across a
/// target's source files.
enum GeneratedSourceBuilder {
    /// - Parameter conformingTypeNames: each conforming type's fully
    ///   namespaced name (e.g. `"GreetingCard"` or `"Feature.GreetingCard"`),
    ///   as written in source. Duplicates are harmless — the generated
    ///   `switch` just gets one `case` per unique name.
    static func makeSource(conformingTypeNames: [String]) -> String {
        let sortedNames = Set(conformingTypeNames).sorted()

        // Deliberately a `switch` over each concrete type name, rather than
        // a lookup through `conformingTypes`. `conformingTypes`' value type,
        // `(any AutoPreviewable).Type`, is an existential — and
        // `previewData`/`previewBuilder(data:)` both mention the erased
        // associated types `PTD`/`PV` in their own signatures, so neither is
        // callable through it. Each `case` below refers to the type by its
        // real name instead, where nothing is erased and both members are
        // ordinary calls on a concrete type — no protocol changes needed.
        //
        // Built via flat, explicit `\n` concatenation rather than nested
        // triple-quoted literals: every line here carries its own complete,
        // hardcoded net indentation (matching how `entries` above already
        // does it), since a nested literal's *own* dedent-stripping doesn't
        // touch a value substituted into it afterward — only string content
        // actually present in the outer literal gets dedented.
        let resolveTestPreviewBody: String
        if sortedNames.isEmpty {
            resolveTestPreviewBody = "        return nil"
        } else {
            let cases = sortedNames
                .map { name in
                    "        case \(swiftStringLiteral(name)):\n"
                    + "            guard let data = \(name).previewData.first(where: { $0.description == dataTag })?.data else { return nil }\n"
                    + "            return AnyView(\(name).previewBuilder(data: data))"
                }
                .joined(separator: "\n")
            resolveTestPreviewBody = "        switch viewTag {\n"
            + cases + "\n"
            + "        default:\n"
            + "            return nil\n"
            + "        }"
        }

        return """
        // Generated by TestablePreviewsPlugin — do not edit.
        //
        // This file is regenerated on every build from whatever types in
        // this module conform to `AutoPreviewable`. It lives only inside
        // the build system's plugin work directory, not in the source
        // tree, and isn't part of this module's public interface.
        import AutoPreview
        import Foundation
        import SwiftUI

        /// A build-time-generated registry of every type in this module
        /// that conforms to `AutoPreviewable`, plus a hook for letting UI
        /// tests substitute one of its previews at runtime. Deliberately
        /// internal (module-private): not exposed as part of this module's
        /// public API.
        final class TestablePreviews {
            /// Returns `content()` normally. In DEBUG builds, if the
            /// process environment has both `TEST_VIEW_TAG` and
            /// `TEST_DATA_TAG` set and they resolve to real preview data,
            /// returns that preview instead — letting a UI test drive a
            /// specific preview state by setting environment variables on
            /// the launched process, rather than getting whatever
            /// `content()` would normally produce.
            @ViewBuilder
            static func setContent(
                testExecutionIdentifier: String = "AUTOPREVIEW_TEST_EXECUTION",
                testViewIdentifier: String = "AUTOPREVIEW_TEST_VIEW",
                testDataIdentifier: String = "AUTOPREVIEW_TEST_DATA",
                @ViewBuilder _ content: @escaping () -> some View
            ) -> some View {
                let defaultContent = content()
                #if DEBUG
                let environment = ProcessInfo.processInfo.environment
                if environment[testExecutionIdentifier] == "true", let testViewTag = environment[testViewIdentifier],
                    let testDataTag = environment[testDataIdentifier],
                    let view = resolveTestPreview(viewTag: testViewTag, dataTag: testDataTag) {
                    view
                } else {
                    defaultContent
                }
                #else
                defaultContent
                #endif
            }

            #if DEBUG
            /// Builds the preview for `viewTag`'s `dataTag` using that
            /// type's own concrete `previewData`/`previewBuilder(data:)`
            /// directly, rather than through `conformingTypes` — its value
            /// type, `(any AutoPreviewable).Type`, is an existential, and
            /// neither `previewData` nor `previewBuilder(data:)` is
            /// callable through it (both mention the erased associated
            /// types `PTD`/`PV` in their own signatures). `viewTag` is
            /// expected to be one of `conformingTypes`' keys; an
            /// unrecognized tag (or one with no data under `dataTag`) just
            /// returns `nil`.
            private static func resolveTestPreview(viewTag: String, dataTag: String) -> AnyView? {
        \(resolveTestPreviewBody)
            }
            #endif
        }
        """
    }

    /// Renders `value` as a double-quoted Swift string literal, escaping
    /// characters that would otherwise break out of the literal. Namespaced
    /// type names can't legally contain most of these, but this stays
    /// defensive rather than assuming it away.
    private static func swiftStringLiteral(_ value: String) -> String {
        let escaped = value
            .replacingOccurrences(of: "\\", with: "\\\\")
            .replacingOccurrences(of: "\"", with: "\\\"")
        return "\"\(escaped)\""
    }
}
